<a href="https://colab.research.google.com/github/Drisatech/Drisa/blob/main/Data_PreProcessing_Preparing_Data_for_Machine_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🔧 Data Preprocessing: Preparing Data for Machine Learning  

Data preprocessing is a critical step in machine learning. Raw data is rarely perfect—it often contains missing values, inconsistent formats, or variables that need to be scaled or encoded. Preprocessing ensures that your data is clean, consistent, and ready for analysis.

---

### Key Steps in Data Preprocessing  

1. **Handling Missing Data:**  
   - Missing values can disrupt machine learning models. Here’s how to handle them:  
     - **Remove Rows/Columns:** If too many values are missing, it may be better to drop the affected rows or columns.  
     - **Imputation:** Replace missing values with an estimate, such as:  
       - The mean, median, or mode of the column.  
       - A placeholder value (e.g., 0 or “unknown”).  
       - Predictions from other data using advanced techniques.  

   - **Example:**  
     | Name    | Age | Salary  |  
     |---------|-----|---------|  
     | Alice   | 25  | 50000   |  
     | Bob     | NaN | 48000   |  
     | Charlie | 30  | NaN     |  
     → Replace NaN with the mean value of the column.  

2. **Encoding Categorical Variables:**  
   - Machine learning models work with numbers, so we need to convert categorical (non-numerical) data into a numerical format:  
     - **Label Encoding:** Assign a unique number to each category.  
       - Example: `["Red", "Blue", "Green"] → [0, 1, 2]`  
     - **One-Hot Encoding:** Create separate binary columns for each category.  
       - Example:  
         | Color  | Red | Blue | Green |  
         |--------|-----|------|-------|  
         | Red    | 1   | 0    | 0     |  
         | Blue   | 0   | 1    | 0     |  
         | Green  | 0   | 0    | 1     |  

3. **Feature Scaling:**  
   - Features (variables) can have vastly different ranges, which can negatively affect models (e.g., distance-based models like KNN).  
   - Scaling ensures that all features contribute equally to the model. Common methods:  
     - **Min-Max Scaling (Normalization):** Rescales values to a range (e.g., 0 to 1).  
       - Formula: `(x - min) / (max - min)`  
     - **Standardization (Z-Score Scaling):** Centers data around 0 with a standard deviation of 1.  
       - Formula: `(x - mean) / std`  

---

### Why Is Data Preprocessing Important?  
- Ensures models can learn effectively from the data.  
- Reduces bias caused by missing or inconsistent data.  
- Improves accuracy and performance of machine learning models.  

Without proper preprocessing, even the best algorithms may fail to deliver meaningful results.

## Example :  Performing Data Preprocessing

#### Step 1: Importing the libraries
**Why?**  
To work with data, we need tools. Think of libraries as toolkits for different jobs:
- **NumPy** helps us do calculations with numbers.
- **Pandas** helps organize and clean data.
- **Matplotlib** (not used here) is for creating graphs to visualize data.  

**How?**  
We load these libraries so we can use their tools in our code.  


In [ ]:
# Step 1: Importing the necessary libraries
# numpy: for numerical operations
# matplotlib: for data visualization (not used in this example, but commonly included)
# pandas: for handling and analyzing datasets

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

#### Step 3: Importing the dataset
**Why?**  
We need data to teach our machine learning model. The dataset is like a spreadsheet, where:
- **Rows** represent different examples (e.g., people, houses, etc.).
- **Columns** represent features (e.g., height, weight, price).  

**How?**  
We load the dataset into our program and split it into two parts:
- **Features (X):** The information we use to make predictions.
- **Target (y):** The thing we want to predict.  

---

In [ ]:
# Import Data Files from Google Drive


import requests
import pandas as pd
from io import StringIO
def read_gd(sharingurl):
    file_id = sharingurl.split('/')[-2]
    download_url='https://drive.google.com/uc?export=download&id=' + file_id
    url = requests.get(download_url).text
    csv_raw = StringIO(url)
    return csv_raw

url = "https://drive.google.com/file/d/1NfbiEKdOxWJ-TR9XZLt6-IXECdSPWUD-/view?usp=drive_link"
gdd = read_gd(url)

df = pd.read_csv(gdd)

dataset = df

dataset

,Country,Age,Salary,Purchased
0,France,44.0,72000.0,No
1,Spain,27.0,48000.0,Yes
2,Germany,30.0,54000.0,No
3,Spain,38.0,61000.0,No
4,Germany,40.0,NaN,Yes
5,France,35.0,58000.0,Yes
6,Spain,NaN,52000.0,No
7,France,48.0,79000.0,Yes
8,Germany,50.0,83000.0,No
9,France,37.0,67000.0,Yes


In [ ]:
# Step 2: Importing the dataset locally
# Load data from a CSV file and separate it into features (X) and target (y).

# dataset = pd.read_csv('sample_data/Data.csv')
X = dataset.iloc[:, :-1].values  # Select all rows and all columns except the last one
y = dataset.iloc[:, -1].values  # Select all rows from the last column

In [ ]:
# Print the feature matrix and target vector to verify the data

print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [ ]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


#### Step 3: Taking care of missing data
**Why?**  
Sometimes data is incomplete (e.g., a person forgot to write their age). Missing data can confuse the model.  

**How?**  
We fill in the blanks with reasonable values. Here, we use the **mean** (average) of the other values in the same column. This way, we don’t lose useful information.  

---

In [ ]:
# Step 3: Handling missing data
# Replace missing values in specific columns with the mean of those columns


from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')  # Define the imputer
imputer.fit(X[:, 1:3]) # Fit the imputer on columns with missing values
X[:, 1:3] = imputer.transform(X[:, 1:3])  # Apply the transformation

In [ ]:
# Print the updated feature matrix
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


#### Step 4:  Encoding categorical data
**Why?**  
Computers don’t understand words like "red" or "cat." They need numbers.  
- For example, "Red, Green, Blue" could become [1, 2, 3].  
Some data might need to be split into multiple columns to avoid confusion (e.g., One-Hot Encoding).  

**How?**  
We convert categories into numbers for:
- **Features:** By creating separate columns for each category (e.g., "Red," "Green," "Blue" become three columns).
- **Target (y):** By assigning numbers to each category (e.g., "Yes" becomes 1, "No" becomes 0).  

---

##### Encoding the Independent Variable

In [ ]:
# Step 4: Encoding categorical data
# Convert categorical data into numeric representations for compatibility with ML algorithms

# Encoding the Independent Variable (categorical feature in the first column)

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))  # Apply one-hot encoding and convert to numpy array

In [ ]:
# Print the updated feature matrix after encoding
print(X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


##### Encoding the Dependent Variable

In [ ]:
# Encoding the Dependent Variable (target variable)

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y) # Convert categories to numeric labels

In [ ]:
# Print the updated target vector
print(y)

[0 1 0 0 1 1 0 1 0 1]


#### Step 5: Splitting the dataset into the Training set and Test set
**Why?**  
We need to test how well our model can predict things it hasn’t seen before. So, we divide the dataset into:
- **Training Set:** Data the model learns from.
- **Test Set:** Data we use to check how well the model has learned.  

**How?**  
We split the data into two parts, often keeping 80% for training and 20% for testing.  

---

In [ ]:
# Step 5: Splitting the dataset into the Training set and Test set
# Separate the data into training and test sets for model evaluation

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [ ]:
# Print the split datasets
print(X_train)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [ ]:
print(X_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [ ]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [ ]:
print(y_test)

[0 1]


#### Step 6: Feature Scaling
**Why?**  
Some features (e.g., age vs. salary) have very different ranges. This can make the model favor one feature over another. For example, if one column has values like 100,000 and another has values like 5, the model might think the bigger numbers are more important.  

**How?**  
We scale all features to the same range so they’re treated equally. This ensures the model focuses on relationships, not just the size of the numbers.  

---

In [ ]:
# Step 6: Feature Scaling
# Standardize features by removing the mean and scaling to unit variance


from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:]) # Fit and transform the training data (only numerical columns)
X_test[:, 3:] = sc.transform(X_test[:, 3:])  # Transform the test data using the same scaler

In [ ]:
# Print the scaled datasets
print(X_train)

[[0.0 0.0 1.0 -0.19159184384578545 -1.0781259408412425]
 [0.0 1.0 0.0 -0.014117293757057777 -0.07013167641635372]
 [1.0 0.0 0.0 0.566708506533324 0.633562432710455]
 [0.0 0.0 1.0 -0.30453019390224867 -0.30786617274297867]
 [0.0 0.0 1.0 -1.9018011447007988 -1.420463615551582]
 [1.0 0.0 0.0 1.1475343068237058 1.232653363453549]
 [0.0 1.0 0.0 1.4379472069688968 1.5749910381638885]
 [1.0 0.0 0.0 -0.7401495441200351 -0.5646194287757332]]


In [ ]:
print(X_test)

[[0.0 1.0 0.0 -1.4661817944830124 -0.9069571034860727]
 [1.0 0.0 0.0 -0.44973664397484414 0.2056403393225306]]


# **Conclusion**

Artificial Intelligence and Machine Learning have transformed how we approach problem-solving, enabling systems to learn from data and make predictions or decisions. In this lecture, we explored the core principles and mathematical foundations underpinning these technologies, along with the data preprocessing steps that form the bedrock of every machine learning project. Remember, the success of any AI system begins with well-prepared data and a strong understanding of the concepts driving it. As you move forward, focus on honing these skills and applying them to real-world challenges. The potential is limitless—what you create with it is up to you!